import { useState, useEffect, useRef, useCallback } from 'react';
import { supabase } from '../supabase';
import { generatePersistentBookmarklet, generatePersistentChapterSyncBookmarklet, generatePersistentHistoryBookmarklet } from '../utils/bookmarklet';

// React blocks javascript: URLs in href as a security measure.
// This component sets the href directly on the DOM node via a ref
// callback, bypassing React's sanitization. This is safe here because
// the URL is generated by our own code, not user input.
function BookmarkletDragLink({ url, label = '📚 Quick Add' }) {
  const setRef = useCallback((node) => {
    if (node) node.href = url;
  }, [url]);

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}>
      <a
        ref={setRef}
        onClick={e => e.preventDefault()}
        style={{
          display: 'inline-block',
          padding: '8px 16px',
          background: 'linear-gradient(135deg, #e04666, #d63384)',
          color: 'white',
          borderRadius: 8,
          fontWeight: 700,
          fontSize: 13,
          textDecoration: 'none',
          cursor: 'grab',
        }}
        title="Drag this to your bookmarks bar"
      >
        {label}
      </a>
      <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>← drag to bookmarks bar</span>
    </div>
  );
}

export default function SettingsView({ userId, session }) {
  const [ao3Username, setAo3Username] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [bookmarkletUrl, setBookmarkletUrl] = useState(null);
  const [chapterSyncUrl, setChapterSyncUrl] = useState(null);
  const [historyUrl, setHistoryUrl] = useState(null);
  const [bmGenerating, setBmGenerating] = useState(false);
  const [bmCopied, setBmCopied] = useState(false);
  const [csCopied, setCsCopied] = useState(false);
  const [hsCopied, setHsCopied] = useState(false);

  useEffect(() => {
    async function loadSettings() {
      try {
        const { data, error } = await supabase
          .from('user_preferences')
          .select('ao3_username')
          .eq('user_id', userId)
          .single();
        if (!error && data) {
          setAo3Username(data.ao3_username || '');
        }
      } catch (e) { console.error('Load settings error:', e); }
      setLoading(false);
    }
    loadSettings();
  }, [userId]);

  async function saveSettings() {
    setSaving(true);
    try {
      const { error } = await supabase
        .from('user_preferences')
        .upsert({ user_id: userId, ao3_username: ao3Username });
      if (error) throw error;
    } catch (e) { console.error('Save error:', e); }
    setSaving(false);
  }

  async function generateBookmarklets() {
    setBmGenerating(true);
    try {
      // Get the current session's refresh token — this lets the bookmarklets
      // auto-refresh the access token on each use, so they don't expire
      const { data: { session: currentSession } } = await supabase.auth.getSession();
      if (!currentSession?.refresh_token) {
        alert('Could not get session. Try signing out and back in.');
        setBmGenerating(false);
        return;
      }
      // Generate all three bookmarklets from the same refresh token
      const [quickAdd, chapterSync, historyImport] = await Promise.all([
        generatePersistentBookmarklet(currentSession.refresh_token),
        generatePersistentChapterSyncBookmarklet(currentSession.refresh_token),
        Promise.resolve(generatePersistentHistoryBookmarklet(currentSession.refresh_token)),
      ]);
      setBookmarkletUrl(quickAdd);
      setChapterSyncUrl(chapterSync);
      setHistoryUrl(historyImport);
    } catch (e) {
      console.error('Bookmarklet generation error:', e);
    }
    setBmGenerating(false);
  }

  async function copyToClipboard(text, setCopiedFn) {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedFn(true);
      setTimeout(() => setCopiedFn(false), 2000);
    } catch (e) {
      // Fallback for iPad Safari which may block clipboard API
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopiedFn(true);
      setTimeout(() => setCopiedFn(false), 2000);
    }
  }

  if (loading) return <div className="loading">Loading settings...</div>;

  return (
    <div className="settings-card">
      <h2>Settings</h2>

      <div className="form-group">
        <label>Account Email</label>
        <input type="email" value={session.user.email} readOnly style={{ color: 'var(--text-muted)' }} />
      </div>

      <div className="form-group">
        <label>AO3 Username</label>
        <input
          type="text"
          placeholder="Your AO3 username"
          value={ao3Username}
          onChange={e => setAo3Username(e.target.value)}
        />
        <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 4 }}>
          Used for server-side bookmark sync in the Import tab. Must match your AO3 profile exactly.
        </div>
      </div>

      <div style={{ display: 'flex', gap: 8, marginBottom: 24 }}>
        <button className="btn btn-accent" onClick={saveSettings} disabled={saving}>
          {saving ? 'Saving...' : 'Save'}
        </button>
      </div>

      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20 }}>
        <h3 style={{ fontSize: 16, marginBottom: 4 }}>AO3 Bookmarklets</h3>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 12, lineHeight: 1.5 }}>
          Two bookmarklets for tracking fics while browsing AO3.
          Works on iPad, iPhone, and desktop — no extension needed.
        </p>

        <div style={{
          display: 'grid',
          gap: 10,
          marginBottom: 14,
          gridTemplateColumns: '1fr 1fr 1fr',
        }}>
          <div style={{ padding: '10px 12px', background: 'var(--surface)', borderRadius: 8, border: '1px solid var(--border)' }}>
            <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 4 }}>📚 Quick Add</div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.4 }}>
              Add a fic to your library with one tap. Instantly marked as "reading."
            </div>
          </div>
          <div style={{ padding: '10px 12px', background: 'var(--surface)', borderRadius: 8, border: '1px solid var(--border)' }}>
            <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 4 }}>📖 Chapter Sync</div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.4 }}>
              Sync your reading progress. Tap on any chapter page to save where you are.
            </div>
          </div>
          <div style={{ padding: '10px 12px', background: 'var(--surface)', borderRadius: 8, border: '1px solid var(--border)' }}>
            <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 4 }}>📜 Reading History</div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.4 }}>
              Import fics from your AO3 reading history. Catches fics you read but never bookmarked.
            </div>
          </div>
        </div>

        <div style={{
          fontSize: 11,
          color: 'var(--text-muted)',
          marginBottom: 14,
          padding: '8px 12px',
          background: 'rgba(224,70,102,0.06)',
          borderRadius: 8,
          border: '1px solid rgba(224,70,102,0.12)',
        }}>
          Need to import your whole AO3 bookmarks library? Use the <strong style={{ color: 'var(--accent)' }}>Bulk Import</strong> bookmarklet in the <strong style={{ color: 'var(--accent)' }}>Import</strong> tab instead.
        </div>

        {!bookmarkletUrl ? (
          <button
            className="btn btn-accent"
            onClick={generateBookmarklets}
            disabled={bmGenerating}
          >
            {bmGenerating ? 'Generating...' : 'Generate Bookmarklets'}
          </button>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {/* Quick Add */}
            <div style={{
              background: 'var(--surface)',
              border: '1px solid var(--border)',
              borderRadius: 10,
              padding: 14,
            }}>
              <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 8 }}>📚 Quick Add</div>
              <BookmarkletDragLink url={bookmarkletUrl} label="📚 Quick Add" />

              <div style={{ display: 'flex', gap: 8, marginBottom: 10 }}>
                <button className="btn btn-accent btn-sm" onClick={() => copyToClipboard(bookmarkletUrl, setBmCopied)}>
                  {bmCopied ? 'Copied!' : 'Copy Quick Add'}
                </button>
              </div>

              <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.5 }}>
                Tap on any AO3 fic page to add it to your library as "reading."
              </div>
            </div>

            {/* Chapter Sync */}
            {chapterSyncUrl && (
              <div style={{
                background: 'var(--surface)',
                border: '1px solid var(--border)',
                borderRadius: 10,
                padding: 14,
              }}>
                <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 8 }}>📖 Chapter Sync</div>
                <BookmarkletDragLink url={chapterSyncUrl} label="📖 Ch. Sync" />

                <div style={{ display: 'flex', gap: 8, marginBottom: 10 }}>
                  <button className="btn btn-accent btn-sm" onClick={() => copyToClipboard(chapterSyncUrl, setCsCopied)}>
                    {csCopied ? 'Copied!' : 'Copy Ch. Sync'}
                  </button>
                </div>

                <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.5 }}>
                  Tap on any chapter page to sync your progress. FicTracker auto-detects which chapter you're on.
                  In the app, "Continue Ch. N on AO3" will take you right back.
                </div>
              </div>
            )}

            {/* Reading History Import */}
            {historyUrl && (
              <div style={{
                background: 'var(--surface)',
                border: '1px solid var(--border)',
                borderRadius: 10,
                padding: 14,
              }}>
                <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 8 }}>📜 Reading History Import</div>
                <BookmarkletDragLink url={historyUrl} label="📜 History Import" />

                <div style={{ display: 'flex', gap: 8, marginBottom: 10 }}>
                  <button className="btn btn-accent btn-sm" onClick={() => copyToClipboard(historyUrl, setHsCopied)}>
                    {hsCopied ? 'Copied!' : 'Copy History Import'}
                  </button>
                </div>

                <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.5 }}>
                  Go to your AO3 Reading History page while logged in, then click this bookmarklet.
                  It imports fics you've read but never bookmarked. Auto-paginates with a 10-second delay.
                  <br /><br />
                  <strong style={{ color: 'var(--text)' }}>Note:</strong> AO3 reading history is private,
                  so this must run in your browser (not server-side). You need to be logged into AO3.
                </div>
              </div>
            )}

            {/* Setup instructions + regenerate */}
            <div style={{
              background: 'var(--surface)',
              border: '1px solid var(--border)',
              borderRadius: 10,
              padding: 14,
            }}>
              <div style={{ fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.6 }}>
                <strong style={{ color: 'var(--text)' }}>Desktop:</strong> Drag the buttons above to your bookmarks bar (Ctrl+Shift+B / Cmd+Shift+B to show it).
                <br /><br />
                <strong style={{ color: 'var(--text)' }}>iPad / iPhone:</strong>
                <ol style={{ margin: '4px 0 0 16px', padding: 0 }}>
                  <li>Tap a "Copy" button above</li>
                  <li>Bookmark any page in Safari</li>
                  <li>Edit the bookmark → replace the URL with the copied text</li>
                  <li>Repeat for the other bookmarklet</li>
                  <li>On any AO3 page, tap the address bar and select the bookmark</li>
                </ol>
              </div>
            </div>

            <button className="btn btn-ghost btn-sm" style={{ alignSelf: 'flex-start' }} onClick={() => { setBookmarkletUrl(null); setChapterSyncUrl(null); setHistoryUrl(null); }}>
              Regenerate Bookmarklets
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
