import { useState, useEffect, useRef, useCallback } from 'react';
import { supabase } from '../supabase';
import { generatePersistentBookmarklet, generatePersistentChapterSyncBookmarklet } from '../utils/bookmarklet';

// React blocks javascript: URLs in href as a security measure.
// This component sets the href directly on the DOM node via a ref
// callback, bypassing React's sanitization. This is safe here because
// the URL is generated by our own code, not user input.
function BookmarkletDragLink({ url, label = '📚 Quick Add' }) {
  const setRef = useCallback((node) => {
    if (node) node.href = url;
  }, [url]);

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}>
      <a
        ref={setRef}
        onClick={e => e.preventDefault()}
        style={{
          display: 'inline-block',
          padding: '8px 16px',
          background: 'linear-gradient(135deg, #e04666, #d63384)',
          color: 'white',
          borderRadius: 8,
          fontWeight: 700,
          fontSize: 13,
          textDecoration: 'none',
          cursor: 'grab',
        }}
        title="Drag this to your bookmarks bar"
      >
        {label}
      </a>
      <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>← drag to bookmarks bar</span>
    </div>
  );
}

export default function SettingsView({ userId, session }) {
  const [ao3Username, setAo3Username] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [bookmarkletUrl, setBookmarkletUrl] = useState(null);
  const [chapterSyncUrl, setChapterSyncUrl] = useState(null);
  const [bmGenerating, setBmGenerating] = useState(false);
  const [bmCopied, setBmCopied] = useState(false);
  const [csCopied, setCsCopied] = useState(false);

  useEffect(() => {
    async function loadSettings() {
      try {
        const { data, error } = await supabase
          .from('user_preferences')
          .select('ao3_username')
          .eq('user_id', userId)
          .single();
        if (!error && data) {
          setAo3Username(data.ao3_username || '');
        }
      } catch (e) { console.error('Load settings error:', e); }
      setLoading(false);
    }
    loadSettings();
  }, [userId]);

  async function saveSettings() {
    setSaving(true);
    try {
      const { error } = await supabase
        .from('user_preferences')
        .upsert({ user_id: userId, ao3_username: ao3Username });
      if (error) throw error;
    } catch (e) { console.error('Save error:', e); }
    setSaving(false);
  }

  async function generateBookmarklets() {
    setBmGenerating(true);
    try {
      // Get the current session's refresh token — this lets the bookmarklets
      // auto-refresh the access token on each use, so they don't expire
      const { data: { session: currentSession } } = await supabase.auth.getSession();
      if (!currentSession?.refresh_token) {
        alert('Could not get session. Try signing out and back in.');
        setBmGenerating(false);
        return;
      }
      // Generate both bookmarklets from the same refresh token
      const [quickAdd, chapterSync] = await Promise.all([
        generatePersistentBookmarklet(currentSession.refresh_token),
        generatePersistentChapterSyncBookmarklet(currentSession.refresh_token),
      ]);
      setBookmarkletUrl(quickAdd);
      setChapterSyncUrl(chapterSync);
    } catch (e) {
      console.error('Bookmarklet generation error:', e);
    }
    setBmGenerating(false);
  }

  async function copyToClipboard(text, setCopiedFn) {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedFn(true);
      setTimeout(() => setCopiedFn(false), 2000);
    } catch (e) {
      // Fallback for iPad Safari which may block clipboard API
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopiedFn(true);
      setTimeout(() => setCopiedFn(false), 2000);
    }
  }

  if (loading) return <div className="loading">Loading settings...</div>;

  return (
    <div className="settings-card">
      <h2>Settings</h2>

      <div className="form-group">
        <label>Account Email</label>
        <input type="email" value={session.user.email} readOnly style={{ color: 'var(--text-muted)' }} />
      </div>

      <div className="form-group">
        <label>AO3 Username (optional)</label>
        <input
          type="text"
          placeholder="Your AO3 username"
          value={ao3Username}
          onChange={e => setAo3Username(e.target.value)}
        />
      </div>

      <div style={{ display: 'flex', gap: 8, marginBottom: 24 }}>
        <button className="btn btn-accent" onClick={saveSettings} disabled={saving}>
          {saving ? 'Saving...' : 'Save'}
        </button>
      </div>

      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20 }}>
        <h3 style={{ fontSize: 16, marginBottom: 4 }}>📚 Quick Add — AO3 Bookmarklet</h3>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 12, lineHeight: 1.5 }}>
          Add a single fic to your library with one click while browsing AO3.
          Tap the bookmarklet on any fic page and it's instantly added as "reading."
          Works on iPad, iPhone, and desktop.
        </p>
        <div style={{
          fontSize: 11,
          color: 'var(--text-muted)',
          marginBottom: 14,
          padding: '8px 12px',
          background: 'rgba(224,70,102,0.06)',
          borderRadius: 8,
          border: '1px solid rgba(224,70,102,0.12)',
        }}>
          Need to import your whole AO3 bookmarks library? Use the <strong style={{ color: 'var(--accent)' }}>Bulk Import</strong> bookmarklet in the <strong style={{ color: 'var(--accent)' }}>Import</strong> tab instead.
        </div>

        {!bookmarkletUrl ? (
          <button
            className="btn btn-accent"
            onClick={generateBookmarklets}
            disabled={bmGenerating}
          >
            {bmGenerating ? 'Generating...' : 'Generate Bookmarklets'}
          </button>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{
              background: 'var(--surface)',
              border: '1px solid var(--border)',
              borderRadius: 10,
              padding: 14,
            }}>
              <BookmarkletDragLink url={bookmarkletUrl} label="📚 Quick Add" />

              <div style={{ fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.6 }}>
                <strong style={{ color: 'var(--text)' }}>Desktop:</strong> Drag the button above to your bookmarks bar. Make sure the bookmarks bar is visible (Ctrl+Shift+B / Cmd+Shift+B) when you're on AO3, then click it on any fic page.
                <br /><br />
                <strong style={{ color: 'var(--text)' }}>iPad / iPhone:</strong>
                <ol style={{ margin: '4px 0 0 16px', padding: 0 }}>
                  <li>Tap "Copy Bookmarklet" below</li>
                  <li>Bookmark any page in Safari</li>
                  <li>Edit the bookmark → replace the URL with the copied text</li>
                  <li>Name it "📚 Quick Add"</li>
                  <li>On any AO3 fic page, tap the address bar and select the bookmark</li>
                </ol>
              </div>
            </div>

            <div style={{ display: 'flex', gap: 8 }}>
              <button className="btn btn-accent btn-sm" onClick={() => copyToClipboard(bookmarkletUrl, setBmCopied)}>
                {bmCopied ? 'Copied!' : 'Copy Bookmarklet'}
              </button>
              <button className="btn btn-ghost btn-sm" onClick={() => { setBookmarkletUrl(null); setChapterSyncUrl(null); }}>
                Regenerate
              </button>
            </div>
          </div>
        )}
      </div>

      {chapterSyncUrl && (
        <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20, marginTop: 20 }}>
          <h3 style={{ fontSize: 16, marginBottom: 4 }}>📖 Chapter Sync — AO3 Bookmarklet</h3>
          <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 12, lineHeight: 1.5 }}>
            Sync your reading progress while browsing AO3.
            Tap this bookmarklet on any chapter page and FicTracker will save which chapter you're on.
            Next time you open the fic in FicTracker, "Continue Ch. N on AO3" will take you right back.
          </p>

          <div style={{
            background: 'var(--surface)',
            border: '1px solid var(--border)',
            borderRadius: 10,
            padding: 14,
            marginBottom: 10,
          }}>
            <BookmarkletDragLink url={chapterSyncUrl} label="📖 Ch. Sync" />

            <div style={{ fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.6 }}>
              <strong style={{ color: 'var(--text)' }}>How it works:</strong> Open any chapter of a fic you've already added to FicTracker, then tap this bookmarklet.
              It auto-detects which chapter you're on and syncs your progress.
              <br /><br />
              <strong style={{ color: 'var(--text)' }}>Tip:</strong> On mobile, set up both bookmarklets — Quick Add for new fics, Chapter Sync for tracking progress.
            </div>
          </div>

          <div style={{ display: 'flex', gap: 8 }}>
            <button className="btn btn-accent btn-sm" onClick={() => copyToClipboard(chapterSyncUrl, setCsCopied)}>
              {csCopied ? 'Copied!' : 'Copy Ch. Sync'}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
