import { useState, useCallback } from 'react';
import { clearAllData, getSettings, saveSettings } from '../storage/local';
import { generateLocalFirstQuickAddBookmarklet } from '../utils/bookmarklet';
import { READING_SPEEDS } from '../utils/helpers';

// React blocks javascript: URLs in href as a security measure.
// We set the href directly on the DOM node to work around this safely —
// the URL is generated by our own code, not user input.
function BookmarkletDragLink({ url, label }) {
  const setRef = useCallback((node) => { if (node) node.href = url; }, [url]);
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}>
      <a
        ref={setRef}
        onClick={e => e.preventDefault()}
        style={{
          display: 'inline-block', padding: '8px 16px',
          background: 'linear-gradient(135deg, #14b8a6, #0d9488)',
          color: 'white', borderRadius: 8, fontWeight: 700,
          fontSize: 13, textDecoration: 'none', cursor: 'grab',
        }}
        title="Drag this to your bookmarks bar"
      >
        {label}
      </a>
      <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>← drag to bookmarks bar</span>
    </div>
  );
}

export default function SettingsView() {
  const [confirmClear, setConfirmClear]   = useState(false);

  const [bookmarkletUrl, setBookmarkletUrl] = useState(null);
  const [bmCopied, setBmCopied]             = useState(false);

  // Reading speed
  const [readingWpm, setReadingWpmState] = useState(() => getSettings().readingWpm || 250);
  function setReadingWpm(wpm) {
    setReadingWpmState(wpm);
    saveSettings({ ...getSettings(), readingWpm: wpm });
  }

  function handleClearData() {
    if (!confirmClear) { setConfirmClear(true); return; }
    clearAllData();
    window.location.reload();
  }

  function generateBookmarklet() {
    // No auth, no server — the bookmarklet parses AO3 metadata in the
    // browser and opens FicTracker with the data in the URL.
    const url = generateLocalFirstQuickAddBookmarklet(window.location.origin);
    setBookmarkletUrl(url);
  }

  async function copyToClipboard(text, setCopied) {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="settings-card">
      <h2>Settings</h2>

      {/* ---------------------------------------------------------------- */}
      {/* Support                                                          */}
      {/* ---------------------------------------------------------------- */}
      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20, marginBottom: 24 }}>
        <h3 style={{ fontSize: 16, marginBottom: 4 }}>☕ Support FicTracker</h3>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 14, lineHeight: 1.5 }}>
          FicTracker is free, ad-free, and always will be. If it saves you time and you want
          to say thanks, a small tip genuinely helps keep it going.
        </p>
        <a
          href="https://ko-fi.com/fictracker"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            padding: '9px 18px',
            background: 'var(--surface)',
            color: 'var(--text)', borderRadius: 8, fontWeight: 700,
            fontSize: 13, textDecoration: 'none',
            border: '1px solid var(--border)',
          }}
        >
          ☕ Buy me a Ko-fi
        </a>
      </div>

      {/* ---------------------------------------------------------------- */}
      {/* Privacy notice                                                   */}
      {/* ---------------------------------------------------------------- */}
      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20, marginBottom: 24 }}>
        <h3 style={{ fontSize: 16, marginBottom: 8 }}>Your data</h3>
        <div style={{
          padding: '12px 16px',
          background: 'rgba(20,184,166,0.06)',
          borderRadius: 10,
          border: '1px solid rgba(20,184,166,0.15)',
          fontSize: 13,
          lineHeight: 1.6,
        }}>
          <div style={{ fontWeight: 700, marginBottom: 4 }}>
            🔒 Local-first — your reading data stays in your browser
          </div>
          <div style={{ color: 'var(--text-muted)' }}>
            Your library, shelves, ratings, and notes are stored in your browser's local storage.
            The only external request FicTracker makes is fetching public AO3 metadata when you
            add a fic by URL — nothing personal is ever sent to a server.
          </div>
        </div>
      </div>

      {/* ---------------------------------------------------------------- */}
      {/* Reading speed                                                    */}
      {/* ---------------------------------------------------------------- */}
      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20, marginBottom: 24 }}>
        <h3 style={{ fontSize: 16, marginBottom: 4 }}>Reading speed</h3>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 14, lineHeight: 1.5 }}>
          Used to estimate how long a fic will take you. Shown on library cards and the fic detail view.
        </p>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
          {[['Slow', READING_SPEEDS.slow], ['Average', READING_SPEEDS.average], ['Fast', READING_SPEEDS.fast]].map(([label, wpm]) => (
            <button
              key={wpm}
              onClick={() => setReadingWpm(wpm)}
              style={{
                padding: '7px 16px', borderRadius: 8, fontSize: 13, fontWeight: 600,
                border: `1px solid ${readingWpm === wpm ? 'var(--accent-teal)' : 'var(--border)'}`,
                background: readingWpm === wpm ? 'rgba(20,184,166,0.1)' : 'var(--surface)',
                color: readingWpm === wpm ? 'var(--accent-teal)' : 'var(--text)',
                cursor: 'pointer',
              }}
            >
              {label} <span style={{ fontWeight: 400, color: 'var(--text-muted)', fontSize: 11 }}>{wpm} wpm</span>
            </button>
          ))}
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <input
              type="number"
              min="50" max="2000"
              value={readingWpm}
              onChange={e => { const v = parseInt(e.target.value); if (v >= 50 && v <= 2000) setReadingWpm(v); }}
              style={{ width: 70, padding: '6px 8px', borderRadius: 8, border: '1px solid var(--border)',
                background: 'var(--surface)', color: 'var(--text)', fontSize: 13 }}
            />
            <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>wpm</span>
          </div>
        </div>
      </div>

      {/* ---------------------------------------------------------------- */}
      {/* Browser extension                                                 */}
      {/* ---------------------------------------------------------------- */}
      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20, marginBottom: 24 }}>
        <h3 style={{ fontSize: 16, marginBottom: 4 }}>Browser Extension</h3>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 14, lineHeight: 1.5 }}>
          The FicTracker extension lives on every AO3 page — add fics, update status, and sync
          chapters without leaving AO3.
        </p>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
          <a
            href="https://chromewebstore.google.com/detail/fictracker/phfdhkgaagelchgejhhpelhcmebomdim"
            target="_blank" rel="noopener noreferrer"
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 8,
              padding: '9px 16px',
              background: 'linear-gradient(135deg, #14b8a6, #0d9488)',
              color: 'white', borderRadius: 8, fontWeight: 700,
              fontSize: 13, textDecoration: 'none',
            }}
          >🧩 Add to Chrome</a>
          <a
            href="https://addons.mozilla.org/en-US/firefox/addon/fictracker/"
            target="_blank" rel="noopener noreferrer"
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 8,
              padding: '9px 16px', background: 'var(--surface)',
              color: 'var(--text)', borderRadius: 8, fontWeight: 700,
              fontSize: 13, textDecoration: 'none', border: '1px solid var(--border)',
            }}
          >🦊 Add to Firefox</a>
        </div>
      </div>

      {/* ---------------------------------------------------------------- */}
      {/* Quick Add bookmarklet                                            */}
      {/* ---------------------------------------------------------------- */}
      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20, marginBottom: 24 }}>
        <h3 style={{ fontSize: 16, marginBottom: 4 }}>📚 Quick Add Bookmarklet</h3>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 6, lineHeight: 1.5 }}>
          Tap on any AO3 work page to add it to your library. FicTracker opens in a new tab
          with the fic pre-loaded — no account, no server, nothing leaves your browser.
        </p>
        <div style={{
          fontSize: 12, color: 'var(--text-muted)', marginBottom: 14,
          padding: '8px 12px', background: 'rgba(20,184,166,0.06)',
          borderRadius: 8, border: '1px solid rgba(20,184,166,0.15)', lineHeight: 1.6,
        }}>
          How it works: the bookmarklet reads the fic's public metadata directly from the AO3
          page in your browser, then passes it to FicTracker via the URL. Nothing is sent to
          any server — not even ours.
        </div>

        {!bookmarkletUrl ? (
          <button className="btn btn-accent" onClick={generateBookmarklet}>
            Generate Quick Add bookmarklet
          </button>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <BookmarkletDragLink url={bookmarkletUrl} label="📚 Quick Add" />
            <div style={{ display: 'flex', gap: 8 }}>
              <button className="btn btn-accent btn-sm" onClick={() => copyToClipboard(bookmarkletUrl, setBmCopied)}>
                {bmCopied ? 'Copied!' : 'Copy bookmarklet'}
              </button>
              <button className="btn btn-ghost btn-sm" onClick={() => setBookmarkletUrl(null)}>
                Regenerate
              </button>
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.6 }}>
              <strong style={{ color: 'var(--text)' }}>Desktop:</strong> Drag the button above to your bookmarks bar (Ctrl+Shift+B / Cmd+Shift+B to show it).<br />
              <strong style={{ color: 'var(--text)' }}>iPad / iPhone:</strong> Tap Copy, bookmark any page in Safari, then edit that bookmark and replace its URL with what you copied.
            </div>
          </div>
        )}

        <div style={{
          marginTop: 16, fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.6,
          padding: '8px 12px', background: 'var(--surface)',
          borderRadius: 8, border: '1px solid var(--border)',
        }}>
          <strong style={{ color: 'var(--text)' }}>Chapter Sync &amp; History Import</strong> are available via the
          browser extension, which can write directly to your local library without any cross-origin
          limitations. Install it from the section above.
        </div>
      </div>

      {/* ---------------------------------------------------------------- */}
      {/* Danger zone                                                       */}
      {/* ---------------------------------------------------------------- */}
      <div style={{ borderTop: '1px solid var(--border)', paddingTop: 20 }}>
        <h3 style={{ fontSize: 16, marginBottom: 8 }}>Danger zone</h3>
        <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 12, lineHeight: 1.5 }}>
          Clearing all data removes your library, shelves, Fic Finder presets, and settings from this
          browser. <strong>Export a backup first</strong> if you want to keep anything.
        </p>
        <button
          style={{
            padding: '8px 16px',
            fontSize: 13,
            fontWeight: 600,
            borderRadius: 8,
            border: '1px solid #e04666',
            background: confirmClear ? '#e04666' : 'transparent',
            color: confirmClear ? '#fff' : '#e04666',
            cursor: 'pointer',
          }}
          onClick={handleClearData}
        >
          {confirmClear ? 'Tap again to confirm — this cannot be undone' : 'Clear all data'}
        </button>
        {confirmClear && (
          <button
            className="btn btn-ghost btn-sm"
            style={{ marginLeft: 10 }}
            onClick={() => setConfirmClear(false)}
          >
            Cancel
          </button>
        )}
      </div>
    </div>
  );
}
